### ISSUE TITLE
Revamp DBMS structure

### ISSUE THREAD

**Issue by sayansil** [sayansil/Ecosystem#1]
The project structure is undergoing massive changes in code as well as data handling standards rapidly and among these changes to handling data in memory, the DBMS has not been updated in a while.

**A complete revamp of the `DatabaseManager` class is required to make it more clear and concise.**
The DB structure needs to be updated to match with the recent needs of the project (if any).

**Comment by DarkStar1997** [comment]
Fixed in [this commit](https://github.com/sayansil/Ecosystem/commit/056ee24289a3ffef7d9a53077f10cbfae5b58262)
