### ISSUE TITLE
Transfer the android app/webapp to new repositories

### ISSUE THREAD

**Issue by sayansil** [sayansil/Ecosystem#53]
This will help users identify the "optional* parts of the repository which are not required to get the flavour of the project. After adding the [GUI realtime graphs](https://github.com/sayansil/Ecosystem/commit/709dd57916b0cdb483943b6b8585f8b5cdcbef37) from ./run, webapps and android app shouldn't be a mandatory part of the core project.

**Comment by sayansil** [comment]
Android app migrated to its [new repository](https://github.com/sayansil/Ecosystem-android).

**Comment by DarkStar1997** [comment]
ez?
