### ISSUE TITLE
Consider missing attributes in fbuffer as default instead of null

### ISSUE THREAD

**Issue by sayansil** [sayansil/Ecosystem#97]
**Describe the bug**
FBuffer omits default value attributes to save memory. Such attributes like `weight_on_speed` must be considered as their default value - in this case 0.0 when not present in the buffer.

In certain scenarios, like in avg world calculation this value is considered null when not present.

**Screenshots**
![Screenshot 2023-05-29 at 12 14 28 AM](https://github.com/sayansil/Ecosystem/assets/16357214/1a04b078-0bbb-4b39-bc83-182b868727ee)

**Comment by DarkStar1997** [comment]
Fixed in 2c46b687643c35749b511c88ee8c715cc0dd3758
